name: Build

on:
  push:
    branches: [main, zig-master]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build
        run: zig build -DCompile_Target=testing -Doptimize=ReleaseFast -DLibrary_Type=Static

      - name: Testing
        run: zig build -Dtest=true test --summary all
